"use client";

import { AlertTriangle, Info } from "lucide-react";
import { cn } from "@/lib/utils";

interface AiDisclaimerProps {
  className?: string;
  variant?: "default" | "compact" | "inline";
}

/**
 * AI Disclaimer Component
 * 
 * Required by ABA Model Rule 5.3 - All AI-generated content must be labeled
 * as requiring attorney review before reliance.
 */
export function AiDisclaimer({ className, variant = "default" }: AiDisclaimerProps) {
  if (variant === "inline") {
    return (
      <span className={cn("text-xs text-amber-600 dark:text-amber-400", className)}>
        <AlertTriangle className="inline h-3 w-3 mr-1" />
        AI-generated — requires attorney review
      </span>
    );
  }

  if (variant === "compact") {
    return (
      <p className={cn(
        "text-xs text-muted-foreground border-l-2 border-amber-400 pl-2 py-0.5",
        className
      )}>
        ⚠️ AI-generated — requires attorney review
      </p>
    );
  }

  return (
    <div className={cn(
      "flex items-start gap-2 p-3 rounded-lg bg-amber-50 dark:bg-amber-950/30 border border-amber-200 dark:border-amber-800",
      className
    )}>
      <Info className="h-4 w-4 text-amber-600 dark:text-amber-400 mt-0.5 shrink-0" />
      <div className="space-y-1">
        <p className="text-sm font-medium text-amber-800 dark:text-amber-200">
          AI-Generated Content
        </p>
        <p className="text-xs text-amber-700 dark:text-amber-300">
          This content was generated by artificial intelligence and requires attorney review 
          before reliance. AI outputs may contain errors, omissions, or inaccuracies. 
          Always verify critical legal information independently.
        </p>
      </div>
    </div>
  );
}

/**
 * Wrapper component for AI-generated content
 * Automatically adds disclaimer below the content
 */
export function AiGeneratedContent({ 
  children, 
  className,
  disclaimerVariant = "compact"
}: { 
  children: React.ReactNode;
  className?: string;
  disclaimerVariant?: "default" | "compact" | "inline";
}) {
  return (
    <div className={cn("space-y-2", className)}>
      {children}
      <AiDisclaimer variant={disclaimerVariant} />
    </div>
  );
}
